import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { trpc } from '@utils/trpc';

const Home: NextPage = () => {
  const hello = trpc.useQuery(['hello', { text: 'John' }]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to TRPC sample app!!!</h1>

        <div className={styles.description}>
          {(() => {
            if (!hello.data) {
              return <div>Loading...</div>;
            } else {
              return (
                <>
                  <p>{hello.data.greeting}!!!</p>
                  <p>authorization is {hello.data.authorization}</p>
                </>
              );
            }
          })()}
        </div>
      </main>
    </div>
  );
};

export default Home;
